// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/ExpertDetail/Aside.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElTag: typeof import('element-plus/es')['ElTag']
    EventItem: typeof import('./src/components/EventItem.vue')['default']
    ExpertPage: typeof import('./src/components/ExpertDetail/ExpertPage.vue')['default']
    ExpertpageAll: typeof import('./src/components/ExpertpageAll.vue')['default']
    FieldsEvent: typeof import('./src/components/FieldsEvent.vue')['default']
    FieldsResults: typeof import('./src/components/FieldsResults.vue')['default']
    Footer: typeof import('./src/components/tkhuyen/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    HomeEvents: typeof import('./src/components/HomeEvents.vue')['default']
    HomeExpert: typeof import('./src/components/HomeExpert.vue')['default']
    HomeFields: typeof import('./src/components/HomeFields.vue')['default']
    HomeHeader: typeof import('./src/components/layouts/HomeHeader.vue')['default']
    HomeNews: typeof import('./src/components/HomeNews.vue')['default']
    'Main&Footer': typeof import('./src/components/ExpertDetail/Main&Footer.vue')['default']
    Mapbox: typeof import('./src/components/Mapbox.vue')['default']
    News: typeof import('./src/components/News.vue')['default']
    NewsItem: typeof import('./src/components/NewsItem.vue')['default']
    RelateExpert: typeof import('./src/components/ExpertDetail/RelateExpert.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}

export { }
