// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Aside: typeof import('./src/components/ExpertDetail/Aside.vue')['default']
    BackupRestore: typeof import('./src/components/BackupRestore.vue')['default']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    EventItem: typeof import('./src/components/EventItem.vue')['default']
    ExpertPage: typeof import('./src/components/ExpertDetail/ExpertPage.vue')['default']
    ExpertpageAll: typeof import('./src/components/ExpertpageAll.vue')['default']
    FieldsEvent: typeof import('./src/components/FieldsEvent.vue')['default']
    FieldsResults: typeof import('./src/components/FieldsResults.vue')['default']
    Footer: typeof import('./src/components/tkhuyen/Footer.vue')['default']
    Header: typeof import('./src/components/layouts/Header.vue')['default']
    HomeEvents: typeof import('./src/components/HomeEvents.vue')['default']
    HomeExpert: typeof import('./src/components/HomeExpert.vue')['default']
    HomeFields: typeof import('./src/components/HomeFields.vue')['default']
    HomeHeader: typeof import('./src/components/layouts/HomeHeader.vue')['default']
    HomeNews: typeof import('./src/components/HomeNews.vue')['default']
    'Main&Footer': typeof import('./src/components/ExpertDetail/Main&Footer.vue')['default']
    Mapbox: typeof import('./src/components/Mapbox.vue')['default']
    News: typeof import('./src/components/News.vue')['default']
    NewsItem: typeof import('./src/components/NewsItem.vue')['default']
    RelateExpert: typeof import('./src/components/ExpertDetail/RelateExpert.vue')['default']
    Search: typeof import('./src/components/Search.vue')['default']
  }
}

export { }
