// Generated by https://quicktype.io

export interface Customer {
    _id: string;
    uid: string;
    gender: number;
    birth: string;
    phone: string;
    address: string;
    email: string;
    image: string;
    interest: string;
    website: string;
    facebook: string;
    linkedIn: string;
    desc: string;
    role: string;
}
