// Generated by https://quicktype.io

export interface DirectRequest {
    last_updated_at: string;
    topic: string[];
    title: string;
    content: string;
    responses: string[];
    expert_id: string;
    customer_id: string;
    status: string;
}
