// Generated by https://quicktype.io

export interface Events {
    _id:        string;
    img:        string;
    web:        string;
    event_name: string;
    location:   string;
    time:       string;
    type:       string;
    desc:       string;
}
