// Generated by https://quicktype.io

export interface Footer {
    twitter: string;
    terms: string;
    facebook: string;
    contact: string;
    team: string;
    linkedin: string;
    slogan: string;
}
