// Generated by https://quicktype.io

export interface ResearchArea {
    _id:     any;
    img:     string;
    keys:    string[];
    des_vn:  string;
    name_vn: string;
    name_en: string;
    des_en:  string;
    status:  string;
}
